name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Core
      run: |
        cd skydb-core
        cargo test --verbose
    - name: Test CLI
      run: |
        cd cli
        cargo test --verbose